### PR TITLE
feat: adds the franklin experimentation engine

### PR DESCRIPTION
**Pull request by ramboz**
Add the Franklin experimentation engine from https://github.com/adobe/aem-experimentation. Also added a demo page in the drafts and hooked into the Milo block rendering to support block-level experiments with an alternate `homepage-brick` component that has a yellow background.

Part of: [MWPW-138479](https://jira.corp.adobe.com/browse/MWPW-138479)
Requires: https://github.com/adobecom/milo/pull/1494

**Test Documents:**
- https://adobe.sharepoint.com/sites/adobecom/Shared%20Documents/Forms/AllItems.aspx?cid=6cca42ee%2Da3ff%2D433f%2D9d5a%2Df3db15862b5e&FolderCTID=0x012000F36D5B4C46F81741BCAC9F03FA9F93D1&id=%2Fsites%2Fadobecom%2FShared%20Documents%2Fhomepage%2Fdrafts%2Framboz&viewid=d776cf70%2D9b7e%2D4ab7%2Db9da%2D9e0f8e03a7d2

**Test URLs:**
- Before: https://main--homepage--ramboz.hlx.live/drafts/ramboz/index-loggedout?martech=off&georouting=off
- After: https://franklin-experimentation--homepage--ramboz.hlx.live/drafts/ramboz/index-loggedout?experiment=demo/challenger-1&milolibs=fix-expblocks&martech=off&georouting=off ([PSI Report](https://pagespeed.web.dev/analysis/https-franklin-experimentation--homepage--ramboz-hlx-live-drafts-ramboz-index-loggedout/yvijq3tgl4?form_factor=mobile))

### CODE REVIEW

**Comment by vgoodric** [comment]
@ramboz Who requested this?  What's the use case?

**Comment by ramboz** [comment]
@vgoodric This was discussed in our recent hackathon with @yesil and @meryllblanchet. The goal is to see if running experiments using the OOTB Franklin engine, instead of Target, has a noticeable performance gain and if we can increase conversion with this

**Comment by vgoodric** [comment]
@ramboz your example seems to be a test.  Does this UED handle personalization?

**Comment by ramboz** [comment]
@vgoodric Correct. And no, not full-on personalization (as in targeting single users) at this point. The Franklin engine is GDPR/HIPAA compliant and only does id-less targeting. We do have limited support for segmentation use cases (as in targeting group of users) though, so you can target mobile vs desktop, or browsers, etc.

**Comment by ramboz** [comment]
Closing in favor of https://github.com/ramboz/homepage/pull/1 for now, so the PR stays in my fork until we are ready to share with the broader audience

**Pull request closed without merging**
